# Copyright (c) Huawei Technologies Co., Ltd. 2025.
# This file is AUTO-GENERATED by gen_test_copy_general.py. DO NOT EDIT DIRECTLY.
import pytest
import torch
import torch_npu  # noqa: F401
import tilelang
import tilelang.language as T
from testcommon import assert_close, gen_tensor

pytestmark = [
    pytest.mark.op('copy_general'),
    pytest.mark.mode('Expert'),
]

DTYPES = ['float16', 'float32']

# ----------------------------------------------------------------------------
# 1. Shape, Rank Mismatch & Memory Continuity Kernels
# ----------------------------------------------------------------------------

def get_kernel_dense_same_rank_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB)
            T.copy(A_UB, B)
    return generated_kernel

def get_kernel_dense_rank_reduced_3d_highest_1_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[0, :, :], A_UB[0, :, :])
            T.copy(A_UB[0, :, :], B[0, :, :])
    return generated_kernel

def get_kernel_dense_rank_reduced_3d_middle_1_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[:, 0, :], A_UB[:, 0, :])
            T.copy(A_UB[:, 0, :], B[:, 0, :])
    return generated_kernel

def get_kernel_dense_rank_reduced_3d_lowest_1_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[:, :, 0], A_UB[:, :, 0])
            T.copy(A_UB[:, :, 0], B[:, :, 0])
    return generated_kernel

def get_kernel_dense_rank_reduced_5d_multi_1_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[0, :, 0, :, 0], A_UB[0, :, 0, :, 0])
            T.copy(A_UB[0, :, 0, :, 0], B[0, :, 0, :, 0])
    return generated_kernel

def get_kernel_true_strided_2d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[16:, 32:96], A_UB)
            T.copy(A_UB, B[16:, 32:96])
    return generated_kernel

def get_kernel_true_strided_3d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[1:3, 4:12, 16:48], A_UB)
            T.copy(A_UB, B[1:3, 4:12, 16:48])
    return generated_kernel

def get_kernel_dense_squeeze_2d_to_1d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[5, :], A_UB)
            T.copy(A_UB, B[5, :])
    return generated_kernel

def get_kernel_dense_squeeze_3d_to_2d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[2, :, :], A_UB)
            T.copy(A_UB, B[2, :, :])
    return generated_kernel

def get_kernel_dense_squeeze_4d_to_2d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[1, 2, :, :], A_UB)
            T.copy(A_UB, B[1, 2, :, :])
    return generated_kernel

def get_kernel_dense_squeeze_5d_to_2d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[1, 0, 3, :, :], A_UB)
            T.copy(A_UB, B[1, 0, 3, :, :])
    return generated_kernel

def get_kernel_dense_squeeze_3d_mid_1_to_2d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[1, :, :], A_UB)
            T.copy(A_UB, B[1, :, :])
    return generated_kernel

def get_kernel_true_strided_squeeze_3d_to_2d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A[2, 8:24, 32:96], A_UB)
            T.copy(A_UB, B[2, 8:24, 32:96])
    return generated_kernel

def get_kernel_dense_expand_1d_to_2d_row_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB[5, :])
            T.copy(A_UB[5, :], B)
    return generated_kernel

def get_kernel_dense_expand_2d_to_3d_plane_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB[2, :, :])
            T.copy(A_UB[2, :, :], B)
    return generated_kernel

def get_kernel_dense_expand_2d_to_4d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB[1, 2, :, :])
            T.copy(A_UB[1, 2, :, :], B)
    return generated_kernel

def get_kernel_dense_expand_1d_1_to_2d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB[0, :1])
            T.copy(A_UB[0, :1], B)
    return generated_kernel

def get_kernel_dense_expand_2d_1_to_4d_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB[1, 2, :, :])
            T.copy(A_UB[1, 2, :, :], B)
    return generated_kernel

def get_kernel_true_strided_expand_2d_to_3d_inner_GM_UB_GM(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(src_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB[2, 16:32, 32:64])
            T.copy(A_UB[2, 16:32, 32:64], B)
    return generated_kernel

def get_kernel_dense_same_rank_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1, A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_rank_reduced_3d_highest_1_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[0, :, :], A_UB2[0, :, :])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_rank_reduced_3d_middle_1_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[:, 0, :], A_UB2[:, 0, :])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_rank_reduced_3d_lowest_1_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[:, :, 0], A_UB2[:, :, 0])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_rank_reduced_5d_multi_1_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[0, :, 0, :, 0], A_UB2[0, :, 0, :, 0])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_true_strided_2d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[16:, 32:96], A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_true_strided_3d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[1:3, 4:12, 16:48], A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_squeeze_2d_to_1d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[5, :], A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_squeeze_3d_to_2d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[2, :, :], A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_squeeze_4d_to_2d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[1, 2, :, :], A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_squeeze_5d_to_2d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[1, 0, 3, :, :], A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_squeeze_3d_mid_1_to_2d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[1, :, :], A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_true_strided_squeeze_3d_to_2d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[2, 8:24, 32:96], A_UB2)
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_expand_1d_to_2d_row_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1, A_UB2[5, :])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_expand_2d_to_3d_plane_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1, A_UB2[2, :, :])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_expand_2d_to_4d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1, A_UB2[1, 2, :, :])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_expand_1d_1_to_2d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1, A_UB2[0, :1])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dense_expand_2d_1_to_4d_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1, A_UB2[1, 2, :, :])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_true_strided_expand_2d_to_3d_inner_UB_UB(src_shape, dst_shape, dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor(src_shape, dtype), B: T.Tensor(dst_shape, dtype)):
        with T.Kernel(1, is_npu=True):
            A_UB1 = T.alloc_ub(src_shape, dtype)
            A_UB2 = T.alloc_ub(dst_shape, dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1, A_UB2[2, 16:32, 32:64])
            T.copy(A_UB2, B)
    return generated_kernel

SHAPE_RANK_PARAMS = [
    ("dense_1d_GM_UB_GM", "GM_UB_GM", (1024,), (1024,), "", "", get_kernel_dense_same_rank_GM_UB_GM),
    ("dense_2d_GM_UB_GM", "GM_UB_GM", (32, 64), (32, 64), "", "", get_kernel_dense_same_rank_GM_UB_GM),
    ("dense_3d_GM_UB_GM", "GM_UB_GM", (8, 16, 32), (8, 16, 32), "", "", get_kernel_dense_same_rank_GM_UB_GM),
    ("dense_4d_GM_UB_GM", "GM_UB_GM", (2, 4, 16, 32), (2, 4, 16, 32), "", "", get_kernel_dense_same_rank_GM_UB_GM),
    ("dense_5d_GM_UB_GM", "GM_UB_GM", (2, 2, 4, 16, 32), (2, 2, 4, 16, 32), "", "", get_kernel_dense_same_rank_GM_UB_GM),
    ("dense_rank_reduced_3d_highest_1_GM_UB_GM", "GM_UB_GM", (1, 32, 64), (1, 32, 64), "0, :, :", "0, :, :", get_kernel_dense_rank_reduced_3d_highest_1_GM_UB_GM),
    ("dense_rank_reduced_3d_middle_1_GM_UB_GM", "GM_UB_GM", (4, 1, 64), (4, 1, 64), ":, 0, :", ":, 0, :", get_kernel_dense_rank_reduced_3d_middle_1_GM_UB_GM),
    ("dense_rank_reduced_3d_lowest_1_GM_UB_GM", "GM_UB_GM", (4, 32, 1), (4, 32, 1), ":, :, 0", ":, :, 0", get_kernel_dense_rank_reduced_3d_lowest_1_GM_UB_GM),
    ("dense_rank_reduced_5d_multi_1_GM_UB_GM", "GM_UB_GM", (1, 4, 1, 32, 1), (1, 4, 1, 32, 1), "0, :, 0, :, 0", "0, :, 0, :, 0", get_kernel_dense_rank_reduced_5d_multi_1_GM_UB_GM),
    ("true_strided_2d_GM_UB_GM", "GM_UB_GM", (32, 128), (16, 64), "16:, 32:96", "", get_kernel_true_strided_2d_GM_UB_GM),
    ("true_strided_3d_GM_UB_GM", "GM_UB_GM", (4, 16, 64), (2, 8, 32), "1:3, 4:12, 16:48", "", get_kernel_true_strided_3d_GM_UB_GM),
    ("dense_squeeze_2d_to_1d_GM_UB_GM", "GM_UB_GM", (16, 128), (128,), "5, :", "", get_kernel_dense_squeeze_2d_to_1d_GM_UB_GM),
    ("dense_squeeze_3d_to_2d_GM_UB_GM", "GM_UB_GM", (4, 16, 64), (16, 64), "2, :, :", "", get_kernel_dense_squeeze_3d_to_2d_GM_UB_GM),
    ("dense_squeeze_4d_to_2d_GM_UB_GM", "GM_UB_GM", (2, 4, 16, 64), (16, 64), "1, 2, :, :", "", get_kernel_dense_squeeze_4d_to_2d_GM_UB_GM),
    ("dense_squeeze_5d_to_2d_GM_UB_GM", "GM_UB_GM", (2, 2, 4, 16, 64), (16, 64), "1, 0, 3, :, :", "", get_kernel_dense_squeeze_5d_to_2d_GM_UB_GM),
    ("dense_squeeze_3d_mid_1_to_2d_GM_UB_GM", "GM_UB_GM", (2, 1, 64), (1, 64), "1, :, :", "", get_kernel_dense_squeeze_3d_mid_1_to_2d_GM_UB_GM),
    ("true_strided_squeeze_3d_to_2d_GM_UB_GM", "GM_UB_GM", (4, 32, 128), (16, 64), "2, 8:24, 32:96", "", get_kernel_true_strided_squeeze_3d_to_2d_GM_UB_GM),
    ("dense_expand_1d_to_2d_row_GM_UB_GM", "GM_UB_GM", (128,), (16, 128), "", "5, :", get_kernel_dense_expand_1d_to_2d_row_GM_UB_GM),
    ("dense_expand_2d_to_3d_plane_GM_UB_GM", "GM_UB_GM", (16, 64), (4, 16, 64), "", "2, :, :", get_kernel_dense_expand_2d_to_3d_plane_GM_UB_GM),
    ("dense_expand_2d_to_4d_GM_UB_GM", "GM_UB_GM", (16, 64), (2, 4, 16, 64), "", "1, 2, :, :", get_kernel_dense_expand_2d_to_4d_GM_UB_GM),
    ("dense_expand_1d_1_to_2d_GM_UB_GM", "GM_UB_GM", (1,), (1, 128), "", "0, :1", get_kernel_dense_expand_1d_1_to_2d_GM_UB_GM),
    ("dense_expand_2d_1_to_4d_GM_UB_GM", "GM_UB_GM", (1, 64), (2, 4, 1, 64), "", "1, 2, :, :", get_kernel_dense_expand_2d_1_to_4d_GM_UB_GM),
    ("true_strided_expand_2d_to_3d_inner_GM_UB_GM", "GM_UB_GM", (16, 32), (4, 64, 128), "", "2, 16:32, 32:64", get_kernel_true_strided_expand_2d_to_3d_inner_GM_UB_GM),
    ("dense_1d_UB_UB", "UB_UB", (1024,), (1024,), "", "", get_kernel_dense_same_rank_UB_UB),
    ("dense_2d_UB_UB", "UB_UB", (32, 64), (32, 64), "", "", get_kernel_dense_same_rank_UB_UB),
    ("dense_3d_UB_UB", "UB_UB", (8, 16, 32), (8, 16, 32), "", "", get_kernel_dense_same_rank_UB_UB),
    ("dense_4d_UB_UB", "UB_UB", (2, 4, 16, 32), (2, 4, 16, 32), "", "", get_kernel_dense_same_rank_UB_UB),
    ("dense_5d_UB_UB", "UB_UB", (2, 2, 4, 16, 32), (2, 2, 4, 16, 32), "", "", get_kernel_dense_same_rank_UB_UB),
    ("dense_rank_reduced_3d_highest_1_UB_UB", "UB_UB", (1, 32, 64), (1, 32, 64), "0, :, :", "0, :, :", get_kernel_dense_rank_reduced_3d_highest_1_UB_UB),
    ("dense_rank_reduced_3d_middle_1_UB_UB", "UB_UB", (4, 1, 64), (4, 1, 64), ":, 0, :", ":, 0, :", get_kernel_dense_rank_reduced_3d_middle_1_UB_UB),
    ("dense_rank_reduced_3d_lowest_1_UB_UB", "UB_UB", (4, 32, 1), (4, 32, 1), ":, :, 0", ":, :, 0", get_kernel_dense_rank_reduced_3d_lowest_1_UB_UB),
    ("dense_rank_reduced_5d_multi_1_UB_UB", "UB_UB", (1, 4, 1, 32, 1), (1, 4, 1, 32, 1), "0, :, 0, :, 0", "0, :, 0, :, 0", get_kernel_dense_rank_reduced_5d_multi_1_UB_UB),
    ("true_strided_2d_UB_UB", "UB_UB", (32, 128), (16, 64), "16:, 32:96", "", get_kernel_true_strided_2d_UB_UB),
    ("true_strided_3d_UB_UB", "UB_UB", (4, 16, 64), (2, 8, 32), "1:3, 4:12, 16:48", "", get_kernel_true_strided_3d_UB_UB),
    ("dense_squeeze_2d_to_1d_UB_UB", "UB_UB", (16, 128), (128,), "5, :", "", get_kernel_dense_squeeze_2d_to_1d_UB_UB),
    ("dense_squeeze_3d_to_2d_UB_UB", "UB_UB", (4, 16, 64), (16, 64), "2, :, :", "", get_kernel_dense_squeeze_3d_to_2d_UB_UB),
    ("dense_squeeze_4d_to_2d_UB_UB", "UB_UB", (2, 4, 16, 64), (16, 64), "1, 2, :, :", "", get_kernel_dense_squeeze_4d_to_2d_UB_UB),
    ("dense_squeeze_5d_to_2d_UB_UB", "UB_UB", (2, 2, 4, 16, 64), (16, 64), "1, 0, 3, :, :", "", get_kernel_dense_squeeze_5d_to_2d_UB_UB),
    ("dense_squeeze_3d_mid_1_to_2d_UB_UB", "UB_UB", (2, 1, 64), (1, 64), "1, :, :", "", get_kernel_dense_squeeze_3d_mid_1_to_2d_UB_UB),
    ("true_strided_squeeze_3d_to_2d_UB_UB", "UB_UB", (4, 32, 128), (16, 64), "2, 8:24, 32:96", "", get_kernel_true_strided_squeeze_3d_to_2d_UB_UB),
    ("dense_expand_1d_to_2d_row_UB_UB", "UB_UB", (128,), (16, 128), "", "5, :", get_kernel_dense_expand_1d_to_2d_row_UB_UB),
    ("dense_expand_2d_to_3d_plane_UB_UB", "UB_UB", (16, 64), (4, 16, 64), "", "2, :, :", get_kernel_dense_expand_2d_to_3d_plane_UB_UB),
    ("dense_expand_2d_to_4d_UB_UB", "UB_UB", (16, 64), (2, 4, 16, 64), "", "1, 2, :, :", get_kernel_dense_expand_2d_to_4d_UB_UB),
    ("dense_expand_1d_1_to_2d_UB_UB", "UB_UB", (1,), (1, 128), "", "0, :1", get_kernel_dense_expand_1d_1_to_2d_UB_UB),
    ("dense_expand_2d_1_to_4d_UB_UB", "UB_UB", (1, 64), (2, 4, 1, 64), "", "1, 2, :, :", get_kernel_dense_expand_2d_1_to_4d_UB_UB),
    ("true_strided_expand_2d_to_3d_inner_UB_UB", "UB_UB", (16, 32), (4, 64, 128), "", "2, 16:32, 32:64", get_kernel_true_strided_expand_2d_to_3d_inner_UB_UB),
]

@pytest.mark.parametrize("dtype", DTYPES)
@pytest.mark.parametrize("desc, direction, src_shape, dst_shape, src_slice_str, dst_slice_str, get_kernel_func", SHAPE_RANK_PARAMS)
def test_shape_rank_mismatch(desc, direction, src_shape, dst_shape, src_slice_str, dst_slice_str, get_kernel_func, dtype):
    kernel_func = get_kernel_func(src_shape, dst_shape, dtype)
    compiled = tilelang.compile(kernel_func, target='npuir')
    
    inp = gen_tensor(src_shape, dtype, kind='randn')
    out_shape = src_shape if direction == "GM_UB_GM" else dst_shape
    out = gen_tensor(out_shape, dtype, kind='zeros')
    compiled(inp, out)
    
    expected_out = torch.zeros_like(out)
    # Use exec to dynamically slice via the string
    
    if direction == "GM_UB_GM":
        src_access = f"[{src_slice_str}]" if src_slice_str else "[:]"
        exec(f"expected_out{src_access} = inp{src_access}")
    else:
        dst_access = f"[{dst_slice_str}]" if dst_slice_str else "[:]"
        src_access = f"[{src_slice_str}]" if src_slice_str else "[:]"
        exec(f"expected_out{dst_access} = inp{src_access}")
        
    assert_close(out.cpu(), expected_out.cpu(), dtype=dtype, rtol=1e-2, atol=1e-2)

# ----------------------------------------------------------------------------
# 2. Dynamic Runtime Bounds Kernels
# ----------------------------------------------------------------------------

def get_kernel_dynamic_from_func_args_GM_UB_GM(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((1024,), dtype), B: T.Tensor((1024,), dtype), shape_N: T.int32):
        with T.Kernel(1, is_npu=True) as (cid, _):
            length = shape_N
            offset = 0
            A_UB = T.alloc_ub((1024,), dtype)
            T.copy(A[offset:offset+length], A_UB[0:length])
            T.copy(A_UB[0:length], B[offset:offset+length])
    return generated_kernel

def get_kernel_dynamic_from_kernel_cid_GM_UB_GM(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((4, 256), dtype), B: T.Tensor((4, 256), dtype)):
        with T.Kernel(4, is_npu=True) as (cid, _):
            row = cid
            offset = 0
            length = 256
            A_UB = T.alloc_ub((256,), dtype)
            T.copy(A[row, offset:offset+length], A_UB[0:length])
            T.copy(A_UB[0:length], B[row, offset:offset+length])
    return generated_kernel

def get_kernel_dynamic_from_for_loop_iterator_GM_UB_GM(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((8, 128), dtype), B: T.Tensor((8, 128), dtype)):
        with T.Kernel(2, is_npu=True) as (cid, _):
            for i in T.serial(4):
                row = cid * 4 + i
                offset = 0
                length = 128
                A_UB = T.alloc_ub((128,), dtype)
                T.copy(A[row, offset:offset+length], A_UB[0:length])
                T.copy(A_UB[0:length], B[row, offset:offset+length])
    return generated_kernel

def get_kernel_dynamic_from_min_max_arithmetic_GM_UB_GM(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((1000,), dtype), B: T.Tensor((1000,), dtype)):
        with T.Kernel(4, is_npu=True) as (cid, _):
            block_size = 256
            offset = cid * 256
            remain = 1000 - offset
            length = T.min(block_size, remain)
            A_UB = T.alloc_ub((256,), dtype)
            T.copy(A[offset:offset+length], A_UB[0:length])
            T.copy(A_UB[0:length], B[offset:offset+length])
    return generated_kernel

def get_kernel_dynamic_loaded_from_ub_buffer_GM_UB_GM(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((4, 256), dtype), Indices: T.Tensor((4,), 'int32'), B: T.Tensor((4, 256), dtype)):
        with T.Kernel(4, is_npu=True) as (cid, _):
            I_UB = T.alloc_ub((4,), 'int32')
            T.copy(Indices, I_UB)
            row = I_UB[cid]
            offset = 0
            length = 256
            A_UB = T.alloc_ub((256,), dtype)
            T.copy(A[row, offset:offset+length], A_UB[0:length])
            T.copy(A_UB[0:length], B[row, offset:offset+length])
    return generated_kernel

def get_kernel_dynamic_from_func_args_UB_UB(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((1024,), dtype), B: T.Tensor((1024,), dtype), shape_N: T.int32):
        with T.Kernel(1, is_npu=True) as (cid, _):
            length = shape_N
            offset = 0
            A_UB1 = T.alloc_ub((1024,), dtype)
            A_UB2 = T.alloc_ub((1024,), dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[0:length], A_UB2[0:length])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dynamic_from_kernel_cid_UB_UB(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((4, 256), dtype), B: T.Tensor((4, 256), dtype)):
        with T.Kernel(4, is_npu=True) as (cid, _):
            row = cid
            offset = 0
            length = 256
            A_UB1 = T.alloc_ub((256,), dtype)
            A_UB2 = T.alloc_ub((256,), dtype)
            T.copy(A[row, :], A_UB1)
            T.copy(A_UB1[0:length], A_UB2[0:length])
            T.copy(A_UB2, B[row, :])
    return generated_kernel

def get_kernel_dynamic_from_for_loop_iterator_UB_UB(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((8, 128), dtype), B: T.Tensor((8, 128), dtype)):
        with T.Kernel(2, is_npu=True) as (cid, _):
            for i in T.serial(4):
                row = cid * 4 + i
                offset = 0
                length = 128
                A_UB1 = T.alloc_ub((128,), dtype)
                A_UB2 = T.alloc_ub((128,), dtype)
                T.copy(A[row, :], A_UB1)
                T.copy(A_UB1[0:length], A_UB2[0:length])
                T.copy(A_UB2, B[row, :])
    return generated_kernel

def get_kernel_dynamic_from_min_max_arithmetic_UB_UB(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((1000,), dtype), B: T.Tensor((1000,), dtype)):
        with T.Kernel(4, is_npu=True) as (cid, _):
            block_size = 256
            offset = cid * 256
            remain = 1000 - offset
            length = T.min(block_size, remain)
            A_UB1 = T.alloc_ub((256,), dtype)
            A_UB2 = T.alloc_ub((256,), dtype)
            T.copy(A, A_UB1)
            T.copy(A_UB1[0:length], A_UB2[0:length])
            T.copy(A_UB2, B)
    return generated_kernel

def get_kernel_dynamic_loaded_from_ub_buffer_UB_UB(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((4, 256), dtype), Indices: T.Tensor((4,), 'int32'), B: T.Tensor((4, 256), dtype)):
        with T.Kernel(4, is_npu=True) as (cid, _):
            I_UB = T.alloc_ub((4,), 'int32')
            T.copy(Indices, I_UB)
            row = I_UB[cid]
            offset = 0
            length = 256
            A_UB1 = T.alloc_ub((256,), dtype)
            A_UB2 = T.alloc_ub((256,), dtype)
            T.copy(A[row, :], A_UB1)
            T.copy(A_UB1[0:length], A_UB2[0:length])
            T.copy(A_UB2, B[row, :])
    return generated_kernel

DYNAMIC_PARAMS = [
    ("dynamic_from_func_args", "GM_UB_GM", get_kernel_dynamic_from_func_args_GM_UB_GM, False),
    ("dynamic_from_kernel_cid", "GM_UB_GM", get_kernel_dynamic_from_kernel_cid_GM_UB_GM, False),
    ("dynamic_from_for_loop_iterator", "GM_UB_GM", get_kernel_dynamic_from_for_loop_iterator_GM_UB_GM, False),
    ("dynamic_from_min_max_arithmetic", "GM_UB_GM", get_kernel_dynamic_from_min_max_arithmetic_GM_UB_GM, False),
    ("dynamic_loaded_from_ub_buffer", "GM_UB_GM", get_kernel_dynamic_loaded_from_ub_buffer_GM_UB_GM, False),
    ("dynamic_from_func_args", "UB_UB", get_kernel_dynamic_from_func_args_UB_UB, False),
    ("dynamic_from_kernel_cid", "UB_UB", get_kernel_dynamic_from_kernel_cid_UB_UB, False),
    ("dynamic_from_for_loop_iterator", "UB_UB", get_kernel_dynamic_from_for_loop_iterator_UB_UB, False),
    ("dynamic_from_min_max_arithmetic", "UB_UB", get_kernel_dynamic_from_min_max_arithmetic_UB_UB, False),
    ("dynamic_loaded_from_ub_buffer", "UB_UB", get_kernel_dynamic_loaded_from_ub_buffer_UB_UB, False),
]

@pytest.mark.parametrize("dtype", DTYPES)
@pytest.mark.parametrize("dyn_case, direction, get_kernel_func, skip", DYNAMIC_PARAMS)
def test_dynamic_scenarios(dyn_case, direction, get_kernel_func, skip, dtype):
    if skip:
        pytest.skip("Dynamic UB->GM tests skipped due to unified memory overflow bugs in simple AST mocking")
        
    kernel_func = get_kernel_func(dtype)
    compiled = tilelang.compile(kernel_func, target='npuir')
    
    if dyn_case == "dynamic_from_func_args":
        inp = gen_tensor((1024,), dtype, kind='randn')
        out = gen_tensor((1024,), dtype, kind='zeros')
        shape_N = 620
        compiled(inp, out, shape_N)
        expected_out = torch.zeros_like(out)
        expected_out[0:shape_N] = inp[0:shape_N]
    elif dyn_case in ("dynamic_from_kernel_cid", "dynamic_from_min_max_arithmetic"):
        shape = (4, 256) if dyn_case == "dynamic_from_kernel_cid" else (1000,)
        inp = gen_tensor(shape, dtype, kind='randn')
        out = gen_tensor(shape, dtype, kind='zeros')
        compiled(inp, out)
        expected_out = torch.zeros_like(out)
        if direction == "GM_UB_GM":
            if dyn_case == "dynamic_from_kernel_cid":
                for cid in range(4):
                    expected_out[cid, 0:256] = inp[cid, 0:256]
            else:
                for cid in range(4):
                    offset = cid * 256
                    remain = 1000 - offset
                    length = min(256, remain)
                    expected_out[offset:offset+length] = inp[offset:offset+length]
        else:
            expected_out[...] = inp[...]
            
    elif dyn_case == "dynamic_from_for_loop_iterator":
        inp = gen_tensor((8, 128), dtype, kind='randn')
        out = gen_tensor((8, 128), dtype, kind='zeros')
        compiled(inp, out)
        expected_out = torch.zeros_like(out)
        if direction == "GM_UB_GM":
            for cid in range(2):
                for i in range(4):
                    row = cid * 4 + i
                    expected_out[row, 0:128] = inp[row, 0:128]
        else:
            expected_out[...] = inp[...]
            
    elif dyn_case == "dynamic_loaded_from_ub_buffer":
        inp = gen_tensor((4, 256), dtype, kind='randn')
        out = gen_tensor((4, 256), dtype, kind='zeros')
        indices = torch.tensor([3, 2, 1, 0], dtype=torch.int32).npu()
        compiled(inp, indices, out)
        expected_out = torch.zeros_like(out)
        for i in range(4):
            if direction == "GM_UB_GM":
                expected_out[indices[i].item(), :] = inp[indices[i].item(), :]
            else:
                expected_out[i, :] = inp[indices[i].item(), :]
            
    assert_close(out.cpu(), expected_out.cpu(), dtype=dtype, rtol=1e-2, atol=1e-2)

# ----------------------------------------------------------------------------
# 3. Explicit vs Implicit Range Syntaxes Kernels
# ----------------------------------------------------------------------------

def get_kernel_syntax_full_tensor(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((128,), dtype), B: T.Tensor((128,), dtype)):
        with T.Kernel(1, is_npu=True) as (cid, _):
            A_UB = T.alloc_ub((128,), dtype)
            T.copy(A, A_UB)
            T.copy(A_UB, B)
    return generated_kernel

def get_kernel_syntax_implicit_src_scalar(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((8, 128), dtype), B: T.Tensor((8, 128), dtype)):
        with T.Kernel(8, is_npu=True) as (cid, _):
            A_UB = T.alloc_ub((128,), dtype)
            T.copy(A[cid, 0:128], A_UB[0:128])
            T.copy(A_UB[0:128], B[cid, 0:128])
    return generated_kernel

def get_kernel_syntax_implicit_dst_scalar(dtype):
    @T.prim_func
    def generated_kernel(A: T.Tensor((8, 128), dtype), B: T.Tensor((8, 128), dtype)):
        with T.Kernel(8, is_npu=True) as (cid, _):
            A_UB = T.alloc_ub((128,), dtype)
            T.copy(A[cid, 0:128], A_UB)
            T.copy(A_UB, B[cid, 0:128])
    return generated_kernel

SYNTAX_PARAMS = [
    ("full_tensor", get_kernel_syntax_full_tensor),
    ("implicit_src_scalar", get_kernel_syntax_implicit_src_scalar),
    ("implicit_dst_scalar", get_kernel_syntax_implicit_dst_scalar),
]

@pytest.mark.parametrize("dtype", DTYPES)
@pytest.mark.parametrize("syntax, get_kernel_func", SYNTAX_PARAMS)
def test_syntax_styles(syntax, get_kernel_func, dtype):
    kernel_func = get_kernel_func(dtype)
    compiled = tilelang.compile(kernel_func, target='npuir')
    shape = (128,) if syntax == "full_tensor" else (8, 128)
    inp = gen_tensor(shape, dtype, kind='randn')
    out = gen_tensor(shape, dtype, kind='zeros')
    compiled(inp, out)
    expected_out = inp.clone()
    assert_close(out.cpu(), expected_out.cpu(), dtype=dtype, rtol=1e-2, atol=1e-2)
